id: '20bd3ed0-1dd1-4788-1fdf-08dcf35ea6f8'
version: 'v1.4'
name: 'ODS'
description: ''
configuration:
  id: 'biGENIUS.Implementation.Generator.Stage.Mssql.File'
  version: '1.7.1'
sourceSystems:
  - id: '30eb9030-2d61-40b3-95f6-d24e9f04d2f6'
    name: 'Adventurework2020'
    description: ''
    sourceSystemTypeId: '9b8ae576-f449-4a79-ae0c-9b8aa2f95cfe'
    activeDiscovery: '52c8b95e-a14b-4993-bd9c-8372786f1af3'
  - id: 'ba651f6b-8709-49bf-8da7-4b0315c8448d'
    name: 'L64_csv'
    description: ''
    sourceSystemTypeId: '9b8ae576-f449-4a79-ae0c-9b8aa2f95cfe'
    activeDiscovery: '98254607-e559-4a24-8361-7b3fb6732c0e'
